kind: pipeline
name: build

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: turboregistry:5000/juju/turbo-ci
      tags: latest
      insecure: true
      registry: turboregistry:5000
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
